install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install glew freetype freeglut
  - vcpkg integrate install
  - cd ..

build_script:
  - msbuild win32\glyphy.sln