install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install glew freetype
  - vcpkg integrate install
  - copy installed\x86-windows\include\freetype2\ft2build.h "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include"
  - xcopy installed\x86-windows\include\freetype2 "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\freetype\" /S
  - xcopy installed\x86-windows\lib "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\"
  - cd ..

  # Someone should put a freeglut on vcpkg but till then, download and install glut manually
  - appveyor DownloadFile https://www.opengl.org/resources/libraries/glut/glutdlls37beta.zip
  - 7z x glutdlls37beta.zip
  - copy glut32.dll "C:\Windows\SysWOW64\"
  - md "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\GL"
  - copy glut.h "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\GL"
  - copy glut32.lib "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib"

build_script:
  - cd win32
  - msbuild glyphy.sln